services:
  - type: web
    name: loop-x-backend
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r server/requirements.txt
    startCommand: python server/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.9
      - key: PORT
        value: 5000
